### ISSUE TITLE
Babysteps

### ISSUE THREAD

**Issue by Joshua27** [ProPra16/programmierpraktikum-abschlussprojekt-nimmdochirgendeinennamen#10]
Es wäre meiner Meinung nach angebracht die verbleibende Zeit in der roten und grünen Phase anzuzeigen, wenn die Babysteps aktiviert sind. Bislang wird der Code einfach ohne Vorwarnung gelöscht.

**Comment by JustARandomName123** [comment]
Habe ein GUI-Element ("lblTimeLeft") zum binden/updaten bereitgestellt.
Babysteps Klasse müsste angepasst werden

**Comment by JustARandomName123** [comment]
Meine Kommentare waren irgendwie sehr uneindeutig. Ich habe nur das GUI Element bereitgestellt, die Implementierung ist nocht nicht erfolgt

**Comment by JustARandomName123** [comment]
Entschuldigung, ich hatte den Branch auf dem es gefixt wurde nicht gesehen

**Comment by cajac101** [comment]
Ich hab so ne leichte Phobie vorm in den masterbranch pushen, hab Angst da was kaputt zu machen ;D

**Comment by iDreamInBinary** [comment]
Brauchst du nicht, man kann jeden Push in 5 sek rückgängig machen 😆
