### ISSUE TITLE
Phasenwechsel

### ISSUE THREAD

**Issue by Joshua27** [ProPra16/programmierpraktikum-abschlussprojekt-nimmdochirgendeinennamen#11]
Ein Wechsel von der Phase RED nach GREEN soll nur möglich sein, wenn mindestens ein Test fehlschlägt. Momentan kann man einfach wechseln ohne einen Test geschrieben zu haben, sofern die Klasse kompiliert.

**Comment by JustARandomName123** [comment]
Danke für die Rückmeldung! Wurde gefixt

**Comment by JulePohlmann** [comment]
Sollte jetzt wieder richtig sein.
(fixing 3e402f7 which broke 0aac883)
