### ISSUE TITLE
Klasse nicht gefunden 

### ISSUE THREAD

**Issue by JulePohlmann** [ProPra16/programmierpraktikum-abschlussprojekt-nimmdochirgendeinennamen#12]
Wie schon gesagt ist es momentan nicht möglich, Tests für eine Klasse zu schreiben, da diese nicht gefunden werden kann.

**Comment by JustARandomName123** [comment]
Problem falsch gedeutet.

<del>Zu wenige Informationen um den Fehler reproduzieren zu können.
Bei mir funktioniert es einwandfrei mit folgenden Operationen:
- shell: gitclone [URL]
- shell: gradle eclipse
- eclipse: Import existing Project
- Erstelle Klasse im Pfad src/main/java/[package X] und zugehörige Testklasse im Pfad src/test/java/[package X].
n einem meiner Tests habe ich folgende Parameter gewählt:
src/main/java/tddt/Basic.java:
[code]
src/test/java/tddt/BasicTest.java:
[code]
Fragen, bei denen der Fehler auftritt:
- Wird eine IDE benutzt, wenn ja, welche?
- Welcher Import-Modi wird benutzt?
- In welchen Pfaden werden Klasse und Testklasse abgelegt?
- Welche exakte Fehlermeldung wird ausgegeben?
</del>

**Comment by JulePohlmann** [comment]
Ich bin nicht ganz sicher, was du meinst, aber eigentlich sollte es doch nicht nötig sein, irgendwelche Klassen manuell zu erstellen, der Nutzer sollte einfach nur das Programm starten müssen.

**Comment by JustARandomName123** [comment]
"Des weiteren kriege ich es nicht hin einen Test in Verbindung mit der Klasse z.B. 'Basic1' zu schreiben, da diese Klasse nicht gefunden werden kann. Das hatte eigentlich schon funktioniert bei euch, aber jetzt nicht mehr." - Joshua Schmidt

Also ist der Test gemeint, der innerhalb des laufenden Programmes geschrieben wird. Ok

**Comment by JustARandomName123** [comment]
Ich vermute, dass es daran liegt, dass die CompilerFactory nicht mehrere CompilationUnits bekommt. Ob dadurch die Sichtbarkeit geregelt wird, ist leider nicht dokumentiert, aber beim überfliegen des Quellcodes sieht es danach aus.

**Comment by JustARandomName123** [comment]
Habe uneleganten fix gepusht.

**Comment by JustARandomName123** [comment]
Habe uneleganten fix gepusht. Sollte ab jetzt funktionieren.
