### ISSUE TITLE
Javadoc authors

### ISSUE THREAD

**Issue by iDreamInBinary** [ProPra16/programmierpraktikum-abschlussprojekt-nimmdochirgendeinennamen#4]
Falls ihr irgendwo zusammengearbeitet habe fügt bitte der vollständigkeit halber den Co-Autor zum author tag hinzu. :8ball: 

Und schaut am besten ob ich die Aufgaben eurer Klassen so richtig interpretiert habe, nicht dass irgendwo Unfug steht :)

@jule34524 @cajac101 @JustARandomName123 @KaiBrandt

**Comment by cajac101** [comment]
Wäre schön wenn man sich vor so was absprechen könnte, die Aufgabe hätte ich gerne noch übernommen. (@Javadoc-Kommentare)

**Comment by iDreamInBinary** [comment]
Ich hab das eigentlich nicht als Aufgabe angesehen, da davon vorher nie wirklich die Rede war, hatte Zeit übrig und hab es dann eben gemacht, dass du das machen wolltest wusste ich nicht :-(

**Comment by iDreamInBinary** [comment]
Ich denke aber auch nicht, dass Kommentare großartig in die Wertung einfließen werden. Aber darüber kann uns wohl nur unser lieber Korrektor @Joshua27 aufklären

**Comment by Joshua27** [comment]
Allgemein solltet ihr euern Code immer ausreichend kommentieren. Hauptsächlich geht es bei dem Projekt natürlich um die Programmierung und die Arbeit im Team.
Die JavaDoc-Kommentare hätten vielleicht eher individuell erstellt werden können, da jeder selbst am besten weiß, was der eigene Code macht. Wie der Kai aber schon geschrieben hat, kann ja jeder nochmal drüber schauen und ggf. die Kommentare erweitern. Daher ist es jetzt kein Problem. Bezogen auf die Gruppenarbeit hätte das aber schon abgesprochen werden können.
Wenn ihr so weiter arbeitet braucht ihr euch eigentlich keine großen Sorgen machen.

**Comment by iDreamInBinary** [comment]
Top :)
