### ISSUE TITLE
gradle stuff

### ISSUE THREAD

**Issue by JustARandomName123** [ProPra16/programmierpraktikum-abschlussprojekt-nimmdochirgendeinennamen#5]
Die Struktur die gradle aufbaut entspricht nicht der unseren, die durch die absoluten Pfade in den Imports gegeben ist.
Der src-Folder wird so garnicht erkannt und verhindert, dass "gradle run" die richtigen Referenzen bekommt.
Ich werde mich morgen dran setzen - wer will kann mitmachen. Bräuchte andere Systeme zum testen.

**Comment by cajac101** [comment]
Wie kann man dir denn helfen?

**Comment by JustARandomName123** [comment]
Die Umstrukturierung ist abgeschlossen
