### ISSUE TITLE
More beautiful tracker logs

### ISSUE THREAD

**Issue by JustARandomName123** [ProPra16/programmierpraktikum-abschlussprojekt-nimmdochirgendeinennamen#6]
Nur ein Vorschlag.

Wenn ein Zeilenumbruch eingefügt wird, wird jede nachfolgende Zeile als neuer Eintrag gewertet.
Man müsste jede Zeile einmal mit einer anderen Zeile vergleichen.
Die Stringfunktion trim() auf jede Zeile würde dann auch Einrückungen berücksichtigen.

**Comment by JulePohlmann** [comment]
Ich versuche schon das ganze noch etwas schöner zu machen, da aber ja morgen Abgabe ist und ich nicht weiß, wie viel ich heute noch schaffe, kann ich nichts versprechen.
