### ISSUE TITLE
Proper thread interrupt

### ISSUE THREAD

**Issue by JustARandomName123** [ProPra16/programmierpraktikum-abschlussprojekt-nimmdochirgendeinennamen#7]
Während der Thread aktiv ist und das Programm (die javafx stage) geschlossen wird, wird der Thread für die Babysteps nicht beendet.

Im Header des Controllers ist ein Lösungsvorschlag, wobei ich mich auch nicht viel weiter informiert habe.

Wie weit ist der fix?

**Comment by cajac101** [comment]
Ist im Backup-Branch gepusht, sollte soweit auch funktionieren =)

**Comment by JustARandomName123** [comment]
https://travis-ci.org/ProPra16/programmierpraktikum-abschlussprojekt-nimmdochirgendeinennamen/builds/144479191

Build schlägt fehl

**Comment by iDreamInBinary** [comment]
Das liegt nur daran, dass der branch uralt ist ... :D

**Comment by iDreamInBinary** [comment]
@cajac101 Entweder in einen neuen Branch, der eine kopie von master ist, pushen 
oder direkt in den master branch :)
