### ISSUE TITLE
Mögliche offene Fragen fürs Handbuch

### ISSUE THREAD

**Issue by cajac101** [ProPra16/programmierpraktikum-abschlussprojekt-nimmdochirgendeinennamen#8]
Welche Fragen könnte man sich als potenzieller Nutzer unseres Programmes denn eurer Meinung nach noch so stellen? 
Ich finde, dass unsere GUI irgendwie selbsterklärend ist, aber ich will nichts übersehen =)

**Comment by JustARandomName123** [comment]
Einen Ablauf mit Erläuterungen bis in den Prozess.
Menü -> Choose Exercise -> etc
Die GUI vielleicht noch um ihre Dialoge erweitern (ExerciseChooser, CatalogBuilder, etc)

**Comment by cajac101** [comment]
Klingt sinnvoll, wird erledigt =)

**Comment by JustARandomName123** [comment]
Mach ein neues Issue auf und poste da den Stacktrace.
Bei mir funktioniert es auf mehreren Systemen.
Zu wenige Informationen, daher:
Bist du denn unter Linux?
Bist du sicher, dass du nicht noch Fragmente von einem alten Gitprojekt in dem Ordner hattest?
Wie hast du das Projekt heruntergeladen?

**Comment by cajac101** [comment]
Wollen wir vielleicht als Standard schon zwei Aufgaben mitliefern, mit denen man dann sofort loslegen kann?

**Comment by iDreamInBinary** [comment]
Gute Idee :+1:
